apiVersion: v1
kind: ConfigMap
metadata:
  name: iam-platform-config
data:
  SPRING_PROFILES_ACTIVE: "dev"
  DB_HOST: "localhost"
  DB_PORT: "5432"
  DB_NAME: "sso_oidc"
  REDIS_HOST: "localhost"
  REDIS_PORT: "6379"
  OIDC_ISSUER_URI: "http://localhost:9000"
  # ZIPKIN_ENDPOINT: "http://localhost:9411/api/v2/spans"  # 可选：需要时取消注释
