apiVersion: v1
kind: Secret
metadata:
  name: iam-platform-secret
type: Opaque
stringData:
  DB_USERNAME: "postgres"
  DB_PASSWORD: "change-me"
  REDIS_PASSWORD: ""
  ENCRYPTION_KEY: "change-me-in-production-32-characters!!"
